=== kate8382/custom-media-platform-showcase/backend/track_data.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Bandcamp track embed data",
    "description": "Schema for Bandcamp embed configuration used by the project's backend",
    "type": "object",
    "properties": {
        "ArtistName": {
            "type": "string"
        },
        "BandcampURL": {
            "type": "string"
        },
        "TotalPublishedTracks": {
            "type": "integer"
        },
        "Tracks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "TrackNumber": {
                        "type": "integer"
                    },
                    "TrackName": {
                        "type": "string"
                    },
                    "BandcampEmbedInfo": {
                        "type": "object",
                        "properties": {
                            "TrackId": {
                                "type": "integer"
                            },
                            "AnchorTrackName": {
                                "type": "string"
                            },
                            "AnchorText": {
                                "type": "string"
                            },
                            "EmbedStyle": {
                                "type": "object",
                                "properties": {
                                    "IFrameSize": {
                                        "type": "string",
                                        "enum": [
                                            "large",
                                            "small"
                                        ]
                                    },
                                    "IFrameWidth": {
                                        "type": "object",
                                        "properties": {
                                            "Amount": {
                                                "type": "integer"
                                            },
                                            "Units": {
                                                "type": "string",
                                                "enum": [
                                                    "px",
                                                    "%"
                                                ]
                                            }
                                        },
                                        "required": [
                                            "Amount",
                                            "Units"
                                        ]
                                    },
                                    "IFrameHeight": {
                                        "type": "object",
                                        "properties": {
                                            "Amount": {
                                                "type": "integer"
                                            },
                                            "Units": {
                                                "type": "string",
                                                "enum": [
                                                    "px",
                                                    "%"
                                                ]
                                            }
                                        },
                                        "required": [
                                            "Amount",
                                            "Units"
                                        ]
                                    },
                                    "BackgroundColor": {
                                        "type": "string",
                                        "minLength": 6,
                                        "maxLength": 6,
                                        "pattern": "^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                                    },
                                    "LinkColor": {
                                        "type": "string",
                                        "minLength": 6,
                                        "maxLength": 6,
                                        "pattern": "^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                                    },
                                    "TrackListShow": {
                                        "type": "boolean"
                                    },
                                    "TransparentShow": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "IFrameSize",
                                    "IFrameWidth",
                                    "IFrameHeight",
                                    "BackgroundColor",
                                    "LinkColor",
                                    "TrackListShow",
                                    "TransparentShow"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "required": [
                            "TrackId",
                            "AnchorText",
                            "AnchorTrackName",
                            "EmbedStyle"
                        ],
                        "additionalProperties": false
                    }
                },
                "required": [
                    "TrackName",
                    "BandcampEmbedInfo"
                ],
                "additionalProperties": false
            },
            "uniqueItems": true
        }
    },
    "required": [
        "ArtistName",
        "BandcampURL",
        "TotalPublishedTracks",
        "Tracks"
    ],
    "additionalProperties": false,
    "examples": [
        {
            "ArtistName": "Example Artist",
            "BandcampURL": "https://example.bandcamp.com",
            "TotalPublishedTracks": 1,
            "Tracks": [
                {
                    "TrackNumber": 1,
                    "TrackName": "Example Track",
                    "BandcampEmbedInfo": {
                        "TrackId": 1811357426,
                        "AnchorTrackName": "example-track",
                        "AnchorText": "Example Track by Example Artist",
                        "EmbedStyle": {
                            "IFrameSize": "large",
                            "IFrameWidth": {
                                "Amount": 280,
                                "Units": "px"
                            },
                            "IFrameHeight": {
                                "Amount": 394,
                                "Units": "px"
                            },
                            "BackgroundColor": "ffffff",
                            "LinkColor": "0687f5",
                            "TrackListShow": false,
                            "TransparentShow": true
                        }
                    }
                }
            ]
        }
    ]
}

=== kate8382/custom-media-platform-showcase/backend/track_data.json
{
    "ArtistName": "Njoy music",
    "BandcampURL": "https://njoy-music.bandcamp.com/",
    "TotalPublishedTracks": 10,
    "Tracks": [
        {
            "TrackNumber": 1,
            "TrackName": "END",
            "BandcampEmbedInfo": {
                "TrackId": 3672841910,
                "AnchorTrackName": "end",
                "AnchorText": "END by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 2,
            "TrackName": "CIA",
            "BandcampEmbedInfo": {
                "TrackId": 626346897,
                "AnchorTrackName": "cia",
                "AnchorText": "CIA by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 3,
            "TrackName": "COL",
            "BandcampEmbedInfo": {
                "TrackId": 929914536,
                "AnchorTrackName": "col",
                "AnchorText": "COL by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 4,
            "TrackName": "FTS",
            "BandcampEmbedInfo": {
                "TrackId": 4139437776,
                "AnchorTrackName": "fts",
                "AnchorText": "FTS by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 5,
            "TrackName": "INA",
            "BandcampEmbedInfo": {
                "TrackId": 2065781303,
                "AnchorTrackName": "ina",
                "AnchorText": "INA by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 6,
            "TrackName": "OUW",
            "BandcampEmbedInfo": {
                "TrackId": 49581169,
                "AnchorTrackName": "ouw",
                "AnchorText": "OUW by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 7,
            "TrackName": "ORD",
            "BandcampEmbedInfo": {
                "TrackId": 264332660,
                "AnchorTrackName": "ord",
                "AnchorText": "ORD by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 8,
            "TrackName": "TOW",
            "BandcampEmbedInfo": {
                "TrackId": 1458026833,
                "AnchorTrackName": "tow",
                "AnchorText": "TOW by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 9,
            "TrackName": "SPE",
            "BandcampEmbedInfo": {
                "TrackId": 2608350280,
                "AnchorTrackName": "spe",
                "AnchorText": "SPE by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        },
        {
            "TrackNumber": 10,
            "TrackName": "ATE",
            "BandcampEmbedInfo": {
                "TrackId": 227286145,
                "AnchorTrackName": "ate",
                "AnchorText": "ATE by Njoy music",
                "EmbedStyle": {
                    "IFrameSize": "large",
                    "IFrameWidth": {
                        "Amount": 260,
                        "Units": "px"
                    },
                    "IFrameHeight": {
                        "Amount": 402,
                        "Units": "px"
                    },
                    "BackgroundColor": "333333",
                    "LinkColor": "e99708",
                    "TrackListShow": false,
                    "TransparentShow": true
                }
            }
        }
    ]
}
